# Generated by Django 5.2.5 on 2025-08-22 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rentalhouse',
            name='size',
        ),
    ]
