# Generated by Django 5.2 on 2025-07-26 11:56

import django.db.models.deletion
import taggit.managers
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_contact_landproperties_housingproperties_and_more'),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='carproperties',
            options={'ordering': ['-created_at'], 'verbose_name': 'Car Property', 'verbose_name_plural': 'Car Properties'},
        ),
        migrations.AlterModelOptions(
            name='housingproperties',
            options={'ordering': ['-created_at'], 'verbose_name': 'Housing Property', 'verbose_name_plural': 'Housing Properties'},
        ),
        migrations.RemoveField(
            model_name='carproperties',
            name='size',
        ),
        migrations.AddField(
            model_name='housingproperties',
            name='house_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('maisonette', 'Maisonette'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('bedsitter', 'Bedsitter'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('cottage', 'Cottage'), ('mansion', 'Mansion'), ('detached', 'Detached House'), ('semi_detached', 'Semi-Detached House')], default='apartment', max_length=255),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='land_type',
            field=models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('agricultural', 'Agricultural'), ('industrial', 'Industrial'), ('mixed_use', 'Mixed Use'), ('recreational', 'Recreational'), ('institutional', 'Institutional')], default='residential', max_length=20),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='latitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='longitude',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='size_unit',
            field=models.CharField(choices=[('acres', 'Acres'), ('sq_ft', 'Square Feet'), ('hectares', 'Hectares')], default='acres', max_length=10),
        ),
        migrations.AddField(
            model_name='landproperties',
            name='tags',
            field=taggit.managers.TaggableManager(blank=True, help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='Tags'),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='fuel_type',
            field=models.CharField(choices=[('petrol', 'Petrol'), ('diesel', 'Diesel'), ('electric', 'Electric'), ('hybrid', 'Hybrid')], default='petrol', max_length=20),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='make',
            field=models.CharField(choices=[('toyota', 'Toyota'), ('honda', 'Honda'), ('ford', 'Ford'), ('chevrolet', 'Chevrolet'), ('nissan', 'Nissan'), ('bmw', 'BMW'), ('audi', 'Audi'), ('mercedes', 'Mercedes-Benz'), ('volkswagen', 'Volkswagen'), ('hyundai', 'Hyundai'), ('kia', 'Kia'), ('subaru', 'Subaru'), ('mazda', 'Mazda'), ('volvo', 'Volvo'), ('land_rover', 'Land Rover'), ('jaguar', 'Jaguar'), ('porsche', 'Porsche'), ('tesla', 'Tesla'), ('other', 'Other')], default='toyota', max_length=50),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='model',
            field=models.CharField(choices=[('corolla', 'Corolla'), ('civic', 'Civic'), ('mustang', 'Mustang'), ('camaro', 'Camaro'), ('altima', 'Altima'), ('3_series', '3 Series'), ('a4', 'A4'), ('c_class', 'C-Class'), ('golf', 'Golf'), ('elantra', 'Elantra'), ('soul', 'Soul'), ('forester', 'Forester'), ('cx_5', 'CX-5'), ('xc60', 'XC60'), ('discovery', 'Discovery'), ('f_type', 'F-Type'), ('911', '911'), ('model_s', 'Model S'), ('model_3', 'Model 3'), ('202', '202'), ('v8', 'V8'), ('suv', 'SUV'), ('pickup', 'Pickup'), ('sedan', 'Sedan'), ('hatchback', 'Hatchback'), ('convertible', 'Convertible'), ('coupe', 'Coupe'), ('wagon', 'Wagon'), ('van', 'Van'), ('other', 'Other')], default='corolla', max_length=50),
        ),
        migrations.AlterField(
            model_name='carproperties',
            name='transmission',
            field=models.CharField(choices=[('manual', 'Manual'), ('automatic', 'Automatic')], default='automatic', max_length=20),
        ),
        migrations.AlterField(
            model_name='housingproperties',
            name='size',
            field=models.CharField(choices=[('studio', 'Studio'), ('bedsitter', 'Bedsitter'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('5_bedroom', '5 Bedroom'), ('6_bedroom', '6 Bedroom'), ('7_plus_bedroom', '7+ Bedroom')], default='studio', max_length=20),
        ),
        migrations.AlterField(
            model_name='landproperties',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='land_properties', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='landproperties',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12),
        ),
        migrations.AlterField(
            model_name='landproperties',
            name='slug',
            field=models.SlugField(blank=True, max_length=255, unique=True),
        ),
    ]
