# Generated by Django 5.2.5 on 2025-08-22 07:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_remove_rentalhouse_size'),
    ]

    operations = [
    ]
