# Generated by Django 5.2 on 2025-07-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_alter_carproperties_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Testimonials',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('subject', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
        migrations.AlterField(
            model_name='housingproperties',
            name='house_type',
            field=models.CharField(choices=[('apartment', 'Apartment'), ('bungalow', 'Bungalow'), ('maisonette', 'Maisonette'), ('duplex', 'Duplex'), ('studio', 'Studio'), ('bedsitter', 'Bedsitter'), ('villa', 'Villa'), ('townhouse', 'Townhouse'), ('penthouse', 'Penthouse'), ('cottage', 'Cottage'), ('mansion', 'Mansion'), ('detached', 'Detached House'), ('semi_detached', 'Semi-Detached House')], default='Apartment', max_length=255),
        ),
        migrations.AlterField(
            model_name='housingproperties',
            name='size',
            field=models.CharField(choices=[('studio', 'Studio'), ('bedsitter', 'Bedsitter'), ('1_bedroom', '1 Bedroom'), ('2_bedroom', '2 Bedroom'), ('3_bedroom', '3 Bedroom'), ('4_bedroom', '4 Bedroom'), ('5_bedroom', '5 Bedroom'), ('6_bedroom', '6 Bedroom'), ('7_plus_bedroom', '7+ Bedroom')], default='Studio', max_length=20),
        ),
    ]
