# Generated by Django 5.2 on 2025-07-30 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0005_newslettersubscriber'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorites',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='listings.carproperties'),
        ),
    ]
