# Generated by Django 5.2 on 2025-07-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0008_faq'),
    ]

    operations = [
        migrations.AddField(
            model_name='carproperties',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='housingproperties',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
    ]
