# Generated by Django 5.2 on 2025-08-16 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0011_amenity_neighborhoodfeature_alter_customuser_role_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingproperties',
            name='amenities',
            field=models.ManyToManyField(related_name='houses', to='listings.amenity'),
        ),
    ]
