# Generated by Django 5.2 on 2025-08-19 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0012_housingproperties_amenities'),
    ]

    operations = [
        migrations.AddField(
            model_name='housingproperties',
            name='is_new',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='housingproperties',
            name='is_sold',
            field=models.BooleanField(default=False),
        ),
    ]
