# Generated by Django 5.2 on 2025-08-21 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0013_housingproperties_is_new_housingproperties_is_sold'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='neighborhoodfeature',
            options={'ordering': ['category', 'name']},
        ),
        migrations.AddField(
            model_name='neighborhoodfeature',
            name='category',
            field=models.CharField(choices=[('education', 'Education'), ('healthcare', 'Healthcare'), ('shopping', 'Shopping'), ('transport', 'Transport'), ('recreation', 'Recreation'), ('other', 'Other')], default='other', max_length=20),
        ),
    ]
