# Generated by Django 5.2 on 2025-08-21 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0014_alter_neighborhoodfeature_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landproperties',
            name='neighborhood',
        ),
        migrations.AddField(
            model_name='landproperties',
            name='neighborhood',
            field=models.ManyToManyField(blank=True, related_name='lands', to='listings.neighborhoodfeature'),
        ),
    ]
